server:
  port: 9090

management:
  endpoints.web.exposure.include: health
  endpoint.health.show-details: always

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/shareit
    username: shareit
    password: shareit

logging:
  level:
    ru.practicum.shareit: DEBUG
    org.springframework:
      orm.jpa: WARN
      transaction: WARN
      transaction.interceptor: WARN
    orm.jpa.JpaTransactionManager: WARN

    org.zalando.logbook: TRACE